import type { Metadata } from "next";  // ✅ correct import
import { Geist, Geist_Mono, Unbounded, Sora } from "next/font/google"; // ✅ import fonts
import "./globals.css";
 

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Nav from "./Components/Nav";
config.autoAddCss = false;

// ✅ Fonts setup
const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Metadata
export const metadata: Metadata = {
  title: "Skyfare Tour & Travel Website",
  description: "Generated by create next app",
};

// ✅ RootLayout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} ${unbounded.variable} ${geist.variable} ${geistMono.variable} antialiased`}
      >
     <Nav/>
        {children}
      </body>
    </html>
  );
}
